### ISSUE TITLE
Cannot install APK after downloading

### ISSUE THREAD

**Issue by AhmerAfzal1** [feicien/android-auto-update#12]
Sample code working good else installing APK after downloading, I'm using Samsung Galaxy S6 having Nougat (7.0). Here is screenshot
![screenshot_20170729-102855](https://user-images.githubusercontent.com/11347099/28742727-28d72d6a-7451-11e7-8f4c-6010a625e961.png)

Please help me @feicien

**Comment by gulullu** [comment]
not work on android 7.0. you should not use Intent on 7.0 when install apk.

**Comment by feicien** [comment]
The problem has been solved
