### ISSUE TITLE
在 Android 8.0 API 26上面不能下载，可以更新一下吗？ 谢谢

### ISSUE THREAD

**Issue by newsco** [feicien/android-auto-update#16]
在 Android 8.0 API 26上面不能下载，可以更新一下吗？ 谢谢

**Comment by feicien** [comment]
代码已经更新了，可以在 Android 8.0 上使用了

**Comment by newsco** [comment]
谢谢。

程辉 <notifications@github.com> 于 2018年4月7日周六 下午5:40写道：
