### ISSUE TITLE
在模拟器2.3.3里面安装apk失败

### ISSUE THREAD

**Issue by dmhai** [feicien/android-auto-update#2]
在模拟器2.3.3里面，显示成功下载，但是安装apk失败，提示：there is a problem parsing the package，在4.0跟4.4.2测试没什么问题。

**Comment by feicien** [comment]
下载的什么apk,是不是该apk不支持 Android 2.3.3 系统了？

**Comment by dmhai** [comment]
不好意思，apk问题，与您的工程无关，我在网上找的测试apk，那个apk很诡异，貌似无法在2.3.3安装，我手动push进去的好像也不行，也是上面那个提示，在高版本则无问题，我没有2.3.3真机可以测试，就暂时不管了。

提几个小建议吧：

①：APP_UPDATE_SERVER_URL 放在UpdateChecker.checkForDialog()传进去会不会好一些？既然都做成lib了，直接可以引用最好，省的还得慢慢翻lib的代码了。

②：调用UpdateChecker.checkForDialog()之后，各种不同情况应该有不同响应。您的代码貌似没有"当前已是最新版本"这类的提示，而且，网络跟服务器问题导致获取不到versionCode，应该也有个回应，不然用户手动按下“检测更新”之后，就石沉大海了，体验不好，当然，启动时候的提示另外考虑。

③：eu.inmite.android.lib.dialogs 只是为了显示dialog？若是的话，可以考虑换一个，现在的开源自定义dialog两三个类就搞定了，没必要那么复杂。或许可以参考安卓自带的dialog改个样式？

④：FragmentActivity 问题。说到dialog了，就顺便说说这个。FragmentActivity参数或许可以考虑移除？我貌似一般都是在Activity或者ActionBarActivity下面写代码，为了一个Update库故意搞个FragmentActivity出来总觉得很别扭。 

上面的话，如果您看着不喜欢，就无视吧。我只是觉得既然当前选用了您的库，应该给您提一下我的看法。

**Comment by feicien** [comment]
谢谢，根据你的建议对代码进行了修改
