### ISSUE TITLE
download 

### ISSUE THREAD

**Issue by akrajilwar** [feicien/android-auto-update#5]
I have received update notification but not download apk file...

**Comment by artwl** [comment]
@akrajilwar you should add service to AndroidManifest.xml

**Comment by akrajilwar** [comment]
I build with sample code...but not working

**Comment by artwl** [comment]
@akrajilwar i forked ths project, add english document here:https://github.com/artwl/android-update-apk/blob/master/README_EN.md

**Comment by akrajilwar** [comment]
Gud...

**Comment by feicien** [comment]
thanks @artwl
